#include "../../apps/external-dealii/step-4/evaluation/native_optimization.hpp"
#include "../../apps/external-dealii/step-4/evaluation/optimization_policy.hpp"
#include "../../apps/external-dealii/step-4/minimal/problem_a_binding.hpp"
#include "../../apps/external-dealii/step-4/verification/verification.hpp"

#include "../dealii/external_step4_evidence.hpp"
#include "../support/scenario_dispatch.hpp"

#include <deal.II/lac/vector.h>

#include <algorithm>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include <stdexcept>
#include <string>
#include <vector>

#include "nmopt/solvers/reduced_gradient.hpp"

namespace
{
  using Backend       = nmopt::dealii_backend::SerialBackend;
  using Binding       = external_dealii_step4::minimal::ProblemABinding;
  using Instrumentation = external_dealii_step4::Instrumentation;
  using NativeReduced = external_dealii_step4::NativeReduced;
  using NativeSolver  = external_dealii_step4::NativeArmijoSolver;
  using OptimizationPolicy = external_dealii_step4::OptimizationPolicy;
  using Parameters    = nmopt::solvers::ReducedSolverParameters;
  using ProblemA      = external_dealii_step4::ProblemA;
  using Matrix        = ProblemA::Matrix;
  using Solver        = nmopt::solvers::ReducedSearchSolverT<Backend>;
  using Vector        = ProblemA::Vector;
  namespace verification = external_dealii_step4::verification;

  struct FreshAudit
  {
    Vector adjoint;
    Vector gradient;
  };

  void
  require(const bool condition, const std::string &message)
  {
    if (!condition)
      {
        external_dealii_step4_test::note_failure(message);
        throw std::runtime_error(message);
      }
  }

  Parameters
  nmopt_parameters(const OptimizationPolicy &policy)
  {
    Parameters parameters;
    parameters.maximum_iterations = policy.maximum_iterations;
    parameters.maximum_line_search_trials = policy.maximum_line_search_trials;
    parameters.gradient_tolerance = policy.gradient_tolerance;
    parameters.stopping_criterion =
      nmopt::solvers::ReducedStoppingCriterion::gradient_norm;
    parameters.relative_gradient_tolerance =
      policy.relative_gradient_tolerance;
    parameters.objective_change_tolerance = policy.objective_change_tolerance;
    parameters.step_tolerance = policy.step_tolerance;
    parameters.objective_target = policy.objective_target;
    parameters.initial_step_length = policy.initial_step_length;
    parameters.minimum_step_length = policy.minimum_step_length;
    parameters.armijo_fraction = policy.armijo_fraction;
    parameters.backtracking_factor = policy.backtracking_factor;
    return parameters;
  }

  double
  vector_difference(const Vector &left, const Vector &right)
  {
    require(left.size() == right.size(),
            "minimal Problem A vectors have incompatible dimensions");
    Vector difference = left;
    difference.add(-1.0, right);
    return difference.l2_norm();
  }

  double
  matrix_difference(const Matrix &left, const Matrix &right)
  {
    require(left.m() == right.m() && left.n() == right.n(),
            "minimal Problem A matrices have incompatible shapes");
    double squared_difference = 0.0;
    for (unsigned int row = 0; row < left.m(); ++row)
      for (unsigned int column = 0; column < left.n(); ++column)
        {
          const double difference =
            left.el(row, column) - right.el(row, column);
          squared_difference += difference * difference;
        }
    return std::sqrt(squared_difference);
  }

  bool
  scalar_matches(const double left, const double right)
  {
    return std::isfinite(left) && std::isfinite(right) &&
           std::abs(left - right) <=
             1.0e-12 + 1.0e-10 * std::max(std::abs(left), std::abs(right));
  }

  FreshAudit
  fresh_audit(ProblemA &problem, const Vector &state, const Vector &control)
  {
    const auto objective_derivative =
      problem.objective_derivative(state, control);
    const auto adjoint = problem.solve_adjoint(objective_derivative.state);
    require(adjoint.evidence.converged,
            "minimal Problem A fresh adjoint solve did not converge");
    const auto control_pullback = problem.control_vjp(adjoint.solution);
    Vector gradient = objective_derivative.control;
    gradient.add(-1.0, control_pullback);
    return {adjoint.solution, std::move(gradient)};
  }

  std::string
  output_payload(const std::filesystem::path &filename)
  {
    std::ifstream input(filename, std::ios::binary);
    require(static_cast<bool>(input),
            "minimal Problem A output could not be opened");
    std::string contents{std::istreambuf_iterator<char>(input),
                         std::istreambuf_iterator<char>()};
    const std::string generated_header =
      "#This file was generated by the deal.II library on ";
    const auto header_start = contents.find(generated_header);
    if (header_start != std::string::npos)
      {
        const auto line_end = contents.find('\n', header_start);
        contents.erase(header_start,
                       line_end == std::string::npos ?
                         contents.size() - header_start :
                         line_end + 1 - header_start);
      }
    return contents;
  }

  void
  check_final_solution(ProblemA &             problem,
                       const Vector &         state,
                       const Vector &         control,
                       const Vector &         returned_adjoint,
                       const Vector &         returned_gradient,
                       const verification::OracleResult &oracle,
                       const std::string &    label)
  {
    verification::require_finite(state, label + " state");
    verification::require_finite(control, label + " control");
    verification::require_finite(returned_adjoint, label + " adjoint");
    verification::require_finite(returned_gradient, label + " gradient");

    const auto state_audit =
      verification::state_equation_residual(problem, state, control);
    const auto fresh = fresh_audit(problem, state, control);
    const auto adjoint_audit =
      verification::adjoint_equation_residual(problem, fresh.adjoint, state);
    require(state_audit.normalized <= 1.0e-10,
            label + " state equation audit failed");
    require(adjoint_audit.normalized <= 1.0e-10,
            label + " adjoint equation audit failed");
    require(vector_difference(returned_adjoint, fresh.adjoint) <= 1.0e-10,
            label + " returned adjoint differs from fresh audit");
    require(vector_difference(returned_gradient, fresh.gradient) <= 1.0e-10,
            label + " returned gradient differs from fresh audit");
    require(fresh.gradient.l2_norm() <= 1.1e-6,
            label + " fresh gradient audit exceeded the acceptance bound");

    const double oracle_distance = vector_difference(control, oracle.control);
    require(oracle_distance <= 2.0e-6,
            label + " control missed the dense oracle");
  }

  void
  run_minimal_problem_a_contract()
  {
    Instrumentation native_instrumentation;
    const auto artifact = external_dealii_step4_test::create_unique_artifact_root(
      std::filesystem::current_path() /
        "runs/external-dealii/step-4/minimal/problem-a",
      "consumer");
    external_dealii_step4_test::EvidenceGuard evidence(
      artifact,
      "minimal_problem_a_binding",
      {{"native", &native_instrumentation}});
    try
      {
        ProblemA native_problem(native_instrumentation);
        NativeReduced native_reduced(native_problem, native_instrumentation);
        const auto policy = external_dealii_step4::frozen_optimization_policy();

        ProblemA minimal_problem;
        Binding binding(minimal_problem);

        require(native_problem.state_dimension() ==
                  minimal_problem.state_dimension(),
                "minimal Problem A state dimensions differ from native reference");
        require(native_problem.control_dimension() ==
                  minimal_problem.control_dimension(),
                "minimal Problem A control dimensions differ from native reference");
        require(matrix_difference(native_problem.system_matrix(),
                                  minimal_problem.system_matrix()) == 0.0,
                "minimal Problem A matrix differs from native reference");
        require(vector_difference(native_problem.system_rhs(),
                                 minimal_problem.system_rhs()) == 0.0,
                "minimal Problem A RHS differs from native reference");

        Vector initial_control(native_problem.control_dimension());
        initial_control = 0.0;
        const auto native_result = NativeSolver(native_reduced, policy).solve(
          initial_control);

        Solver solver(binding.reduced(),
                      binding.metric(),
                      nmopt_parameters(policy));
        const auto minimal_result = solver.solve(
          nmopt::contract::PrimalBlockT<Backend>(binding.control_layout(),
                                                 {initial_control}));

        require(native_result.stopping_reason ==
                  external_dealii_step4::NativeOptimizationStoppingReason::
                    gradient_tolerance,
                "native Problem A reference did not stop by gradient tolerance");
        require(minimal_result.stopping_reason ==
                  nmopt::solvers::ReducedStoppingReason::gradient_tolerance,
                "minimal Problem A consumer did not stop by gradient tolerance");
        require(native_result.accepted_iteration_count ==
                  minimal_result.accepted_iterations,
                "minimal Problem A accepted-iteration count differs from native");
        require(native_result.line_search_trial_count ==
                  minimal_result.line_search_trial_count,
                "minimal Problem A trial count differs from native");

        const auto oracle = verification::optimum_oracle(native_problem);
        require(oracle.system_residual <= 1.0e-10 &&
                  oracle.stationarity_residual <= 1.0e-10,
                "minimal Problem A dense oracle audit failed");

        const auto &native_state = native_result.value.state;
        const auto &native_control = native_result.value.control;
        const auto &minimal_state = minimal_result.final_evaluation.state.block(0);
        const auto &minimal_control = minimal_result.control.block(0);
        const auto &minimal_adjoint =
          minimal_result.final_evaluation.adjoint.block(0);
        const auto &minimal_gradient =
          minimal_result.final_evaluation.reduced_derivative.block(0);

        require(vector_difference(native_state, minimal_state) <= 1.0e-10,
                "minimal Problem A state differs from native reference");
        require(vector_difference(native_control, minimal_control) <= 1.0e-10,
                "minimal Problem A control differs from native reference");
        require(scalar_matches(native_result.value.objective,
                               minimal_result.final_evaluation.objective_value),
                "minimal Problem A objective differs from native reference");
        require(native_result.derivative.reduced_derivative.l2_norm() <=
                  policy.gradient_tolerance &&
                  minimal_result.gradient_norm_history.back() <=
                    policy.gradient_tolerance,
                "minimal Problem A final gradient did not meet tolerance");

        check_final_solution(native_problem,
                             native_state,
                             native_control,
                             native_result.derivative.adjoint,
                             native_result.derivative.reduced_derivative,
                             oracle,
                             "native Problem A");
        check_final_solution(minimal_problem,
                             minimal_state,
                             minimal_control,
                             minimal_adjoint,
                             minimal_gradient,
                             oracle,
                             "minimal Problem A");

        const auto native_output = artifact / "native-solution.vtk";
        const auto minimal_output = artifact / "minimal-solution.vtk";
        native_problem.output_results(native_state, native_output);
        minimal_problem.output_results(minimal_state, minimal_output);
        require(output_payload(native_output) == output_payload(minimal_output),
                "minimal Problem A output differs from native reference");

        evidence.complete();
      }
    catch (...)
      {
        evidence.fail_current_exception();
        throw;
      }
  }
} // namespace

int
main(const int argc, char **argv)
{
  try
    {
      const std::vector<nmopt::test_support::Scenario> scenarios{
        {"minimal_problem_a_binding",
         "nmopt.external.tutorial_step_4.minimal_problem_a_binding_contract",
         {"dealii", "application", "external", "minimal", "problem_a"},
         360,
         run_minimal_problem_a_contract}};
      const auto result = nmopt::test_support::run_requested_scenarios(
        argc, argv, scenarios, std::cout);
      if (!result.listed)
        std::cout << "minimal Problem A binding contract passed: "
                  << result.executed << '\n';
      return 0;
    }
  catch (const std::exception &exception)
    {
      std::cerr << "minimal Problem A binding contract failed: "
                << exception.what() << '\n';
      return 1;
    }
}
